import { Funfic } from '../models/funfic.model';

export const funficResponse: Funfic[] = [
  {
    id: '1',
    name: 'name',
    author: 'author',
    genre: 'fantasy',
    rating: 4.84,
    scoreCount: 3024,
    chaptersCount: 15,
    shortDescription: 'this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla',
    createdAt: '2021-02-18T14:16:12.000Z',
    tags: ['shit', 'dew', 'ehh']
  },
  {
    id: '2',
    name: 'name',
    author: 'author',
    genre: 'fantasy',
    rating: 4.84,
    scoreCount: 3024,
    chaptersCount: 15,
    shortDescription: 'this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla',
    createdAt: '2021-02-18T14:16:12.000Z',
    tags: ['shit', 'dew', 'ehh']
  },
  {
    id: '3',
    name: 'name',
    author: 'author',
    genre: 'fantasy',
    rating: 4.84,
    scoreCount: 3024,
    chaptersCount: 15,
    shortDescription: 'this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla',
    createdAt: '2021-02-18T14:16:12.000Z',
    tags: ['shit', 'dew', 'ehh']
  },
  {
    id: '4',
    name: 'name',
    author: 'author',
    genre: 'fantasy',
    rating: 4.84,
    scoreCount: 3024,
    chaptersCount: 15,
    shortDescription: 'this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla',
    createdAt: '2021-02-18T14:16:12.000Z',
    tags: ['shit', 'dew', 'ehh', 'shit', 'dew', 'ehh', 'shit', 'dew', 'ehh', 'shit', 'dew', 'ehh']
  },
  {
    id: '5',
    name: 'name',
    author: 'author',
    genre: 'fantasy',
    rating: 4.84,
    scoreCount: 3024,
    chaptersCount: 15,
    shortDescription: 'this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla',
    createdAt: '2021-02-18T14:16:12.000Z',
    tags: ['shit', 'dew', 'ehh']
  },
  {
    id: '6',
    name: 'name',
    author: 'author',
    genre: 'fantasy',
    rating: 4.84,
    scoreCount: 3024,
    chaptersCount: 15,
    shortDescription: 'this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla',
    createdAt: '2021-02-18T14:16:12.000Z',
    tags: ['shit', 'dew', 'ehh']
  },
  {
    id: '7',
    name: 'name',
    author: 'author',
    genre: 'fantasy',
    rating: 4.84,
    scoreCount: 3024,
    chaptersCount: 15,
    shortDescription: 'this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla',
    createdAt: '2021-02-18T14:16:12.000Z',
    tags: ['shit', 'dew', 'ehh']
  },
  {
    id: '8',
    name: 'name',
    author: 'author',
    genre: 'fantasy',
    rating: 4.84,
    scoreCount: 3024,
    chaptersCount: 15,
    shortDescription: 'this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla',
    createdAt: '2021-02-18T14:16:12.000Z',
    tags: ['shit', 'dew', 'ehh']
  },
  {
    id: '9',
    name: 'name',
    author: 'author',
    genre: 'fantasy',
    rating: 4.84,
    scoreCount: 3024,
    chaptersCount: 15,
    shortDescription: 'this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla',
    createdAt: '2021-02-18T14:16:12.000Z',
    tags: ['shit', 'dew', 'ehh', 'shit', 'dew', 'ehh', 'shit', 'dew', 'ehh', 'shit', 'dew', 'ehh']
  },
  {
    id: '10',
    name: 'name',
    author: 'author',
    genre: 'fantasy',
    rating: 4.84,
    scoreCount: 3024,
    chaptersCount: 15,
    shortDescription: 'this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla',
    createdAt: '2021-02-18T14:16:12.000Z',
    tags: ['shit', 'dew', 'ehh']
  },
  {
    id: '11',
    name: 'name',
    author: 'author',
    genre: 'fantasy',
    rating: 4.84,
    scoreCount: 3024,
    chaptersCount: 15,
    shortDescription: 'this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla',
    createdAt: '2021-02-18T14:16:12.000Z',
    tags: ['shit', 'dew', 'ehh']
  },
  {
    id: '12',
    name: 'name',
    author: 'author',
    genre: 'fantasy',
    rating: 4.84,
    scoreCount: 3024,
    chaptersCount: 15,
    shortDescription: 'this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla',
    createdAt: '2021-02-18T14:16:12.000Z',
    tags: ['shit', 'dew', 'ehh']
  },
  {
    id: '13',
    name: 'name',
    author: 'author',
    genre: 'fantasy',
    rating: 4.84,
    scoreCount: 3024,
    chaptersCount: 15,
    shortDescription: 'this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla',
    createdAt: '2021-02-18T14:16:12.000Z',
    tags: ['shit', 'dew', 'ehh']
  },
  {
    id: '14',
    name: 'name',
    author: 'author',
    genre: 'fantasy',
    rating: 4.84,
    scoreCount: 3024,
    chaptersCount: 15,
    shortDescription: 'this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla',
    createdAt: '2021-02-18T14:16:12.000Z',
    tags: ['shit', 'dew', 'ehh', 'shit', 'dew', 'ehh', 'shit', 'dew', 'ehh', 'shit', 'dew', 'ehh']
  },
  {
    id: '15',
    name: 'name',
    author: 'author',
    genre: 'fantasy',
    rating: 4.84,
    scoreCount: 3024,
    chaptersCount: 15,
    shortDescription: 'this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla this is story about blablabla',
    createdAt: '2021-02-18T14:16:12.000Z',
    tags: ['shit', 'dew', 'ehh']
  }
];
