export const tagsResponse: string[] = [
  'fantasy',
  'erotica',
  'comedy',
  '18+',
  'harry potter',
  'lotr',
  'lord of the rings',
  'fantasy',
  'erotica',
  'comedy',
  '18+',
  'harry potter',
  'lotr',
  'lord of the rings', 'fantasy',
  'erotica',
  'comedy',
  '18+',
  'harry potter',
  'lotr',
  'lord of the rings',
];
